// Package config handles minimal server configuration via CLI flags.
// Most settings are now managed through the web interface and stored in SQLite.
package config

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strconv"
	"strings"
)

// Config holds minimal server configuration from CLI flags.
// All other settings are loaded from the database at runtime.
type Config struct {
	// Port is the TCP port the HTTP server listens on.
	Port int
	// Host is the network interface to bind to (e.g., "0.0.0.0", "127.0.0.1").
	Host string
	// Dirs is the ordered list of root directories to serve.
	Dirs []string
	// DataDir is the directory for all persistent data (database, uploads, etc.).
	// All files generated by this program are contained within this directory.
	DataDir string
	// TrustedProxy is an optional IP/CIDR for reverse proxy setup.
	TrustedProxy string
}

// dirList is a custom flag.Value that can be set multiple times.
type dirList []string

func (d *dirList) String() string {
	return strings.Join(*d, ", ")
}

func (d *dirList) Set(value string) error {
	*d = append(*d, value)
	return nil
}

// Load parses CLI flags and environment variables, returning a validated Config.
// Only essential runtime configuration is handled here; all UI and feature settings
// are now managed through the web interface.
func Load() (*Config, error) {
	var dirs dirList
	portFlag := flag.Int("port", 0, "HTTP port to listen on (env: GILE_PORT, default: 7887)")
	hostFlag := flag.String("host", "", "Network interface to bind to (env: GILE_HOST, default: 0.0.0.0)")
	dataDirFlag := flag.String("data-dir", "", "Directory for all persistent data - database, uploads, etc. (env: GILE_DATA_DIR, default: ./giledata)")
	trustedProxyFlag := flag.String("trusted-proxy", "", "IP or CIDR of trusted reverse proxy (env: GILE_TRUSTED_PROXY)")
	flag.Var(&dirs, "dir", "Root directory to serve (repeatable; env: GILE_DIRS, colon-separated)")
	flag.Parse()

	// --- port ---
	port := *portFlag
	if port == 0 {
		if v := os.Getenv("GILE_PORT"); v != "" {
			p, err := strconv.Atoi(v)
			if err != nil || p < 1 || p > 65535 {
				return nil, fmt.Errorf("invalid GILE_PORT value %q", v)
			}
			port = p
		} else {
			port = 7887
		}
    }

	// --- host ---
	host := *hostFlag
	if host == "" {
        host = os.Getenv("GILE_HOST")
    }
	if host == "" {
        host = "0.0.0.0"
    }

	// --- dirs ---
	if len(dirs) == 0 {
		if v := os.Getenv("GILE_DIRS"); v != "" {
			for _, d := range strings.Split(v, ":") {
                d = strings.TrimSpace(d)
                if d != "" {
                    dirs = append(dirs, d)
                }
            }
        }
    }

	// Remaining positional arguments are also treated as directories
	for _, arg := range flag.Args() {
        dirs = append(dirs, arg)
    }

	// --- data-dir ---
	dataDir := *dataDirFlag
	if dataDir == "" {
        if v := os.Getenv("GILE_DATA_DIR"); v != "" {
            dataDir = v
        } else {
            dataDir = "giledata"
        }
    }

	// Create data directory if it doesn't exist.
	if err := os.MkdirAll(dataDir, 0755); err != nil {
        return nil, fmt.Errorf("could not create data directory %q: %w", dataDir, err)
    }

	// --- trusted-proxy ---
	trustedProxy := *trustedProxyFlag
	if trustedProxy == "" {
        trustedProxy = os.Getenv("GILE_TRUSTED_PROXY")
    }

	// Validate directories if any were specified.
	// Note: Directories can now be managed via the web interface, so zero dirs is allowed.
	for _, d := range dirs {
        info, err := os.Stat(d)
        if err != nil {
            return nil, fmt.Errorf("directory %q: %w", d, err)
        }
        if !info.IsDir() {
            return nil, fmt.Errorf("%q is not a directory", d)
        }
    }

	log.Printf("config: loaded CLI flags - port=%d host=%s dirs=%v data-dir=%s",
        port, host, dirs, dataDir)

	return &Config{
        Port:         port,
        Host:         host,
        Dirs:         []string(dirs),
        DataDir:      dataDir,
        TrustedProxy: trustedProxy,
    }, nil
}
